=== sandialabs/dgm/schemas/newSchema.json
{
  "$schema" : "http://json-schema.org/schema#",
  "title" : "Test schema",
  "description" : "This is a test of a DGM schema using references",
  "type" : "object",
  "required" : [ "Title", "Domain" ],
  "properties" : {
    "Title" : { "type" : "string" },
    "Problem" : { "$ref" : "Problem.json#" },
    "Domain" : { "$ref" : "Domain.json#" },
    "AdvDiff" : { "$ref" : "AdvDiff.json#" },
    "InCore" : { "$ref" : "InCore.json#" },
    "Griewank" : { "$ref" : "Griewank.json#" },
    "Slice" : { "$ref" : "Slice.json#" },
    "Solver" : { "$ref" : "Solver.json#" },
    "Zoltan" : { "$ref" : "Zoltan.json#" },
    "Field Slice" : { "$ref" : "Slice.json#" }
  },
  "additionalProperties" : false 
}

=== sandialabs/dgm/runs/json/2d/2d.json
{
  "Title" : "Two-dimensional advection diffusion test problem",
  "Problem" : {
    "Type" : "Reo"
  },
  "Domain" : {
    "Verbosity" : 0, 
    "Type" : "Advection diffusion",
    "Advection diffusion" : {
      "Verbosity" : 0,
      "cx" : 1.0,
      "cy" : 0.0,
      "vis" : 0.01
    },
    "Time" : {
      "Integrator" : "DTK::TimeIntegrate",
      "Method" : "TVD",
      "Nt" : 1000,
      "Ntout" : 1000,
      "ntout" : 100,
      "dt" : 0.002
    },
    "Space" : {
      "bmesh" : true,
      "p" : 10 
    }
  },
  "Field Slice" : [ {
    "Verbosity" : 0,
    "Format" : "float",
    "Frequency" : 1000,
    "Lattice" : [ [ 0.1, 0.0 ], [ 0.0, 0.1 ] ],
    "Outputs" : [ { "Default" : 0.0, "Field" : "u", "File" : "2d.u" } ]
  } ]
}

=== sandialabs/dgm/schemas/new.json
{ 
  "Title" : "Test of the newSchema validation",
  "Domain" : { },
  "AdvDiff" : { 
    "Wave speed" : [ 1.0, 0, 0 ],
    "cfield" : false,
    "Variable convective field" : true,
    "cx" : 1.0, "cy" : 0, "cz" : 0
  },
  "Griewank" : {
    "Statistics" : 1, 
    "Number of Snapshots" : 1 
  },
  "InCore" : { 
    "Processors per node" : 1,
    "Percent of memory to use" : 80 
  },
  "Solver" : { "Read parameters from XML" : false },
  "Zoltan" : { "Partition" : { "algorithm" : "rcb" } }
}
