=== sandialabs/dgm/schemas/Response.json
{
  "$schema" : "http://json-schema.org/schema#",
  "title" : "Response",
  "description" : "Schema for the new DGM::Response",
  "type" : "object",
  "required" : [
    "Probes",
    "Kernels"
  ],
  "properties" : {
    "Name" : {
      "type" : "string"
    },
    "Verbosity" : {
      "type" : "integer",
      "minimum" : 0,
      "maximum" : 3,
      "default" : 0
    },
    "Format" : {
      "type" : "string",
      "default" : "ascii",
      "enum" : [
        "ascii",
        "double",
        "float"
      ],
      "description" : "File format for Response data"
    },
    "Type" : {
      "type" : "string",
      "default" : "default",
      "enum" : [
        "default",
        "separate",
        "combined"
      ],
      "description" : "File type for Response data"
    },
    "Transposed" : {
      "type" : "boolean",
      "default" : false,
      "description" : "Default is probe, time"
    },
    "Time trace" : {
      "type" : "boolean",
      "default" : false,
      "description" : "Whether there is a time probe"
    },
    "Max open files" : {
      "type" : "integer",
      "default" : 1,
      "description" : "How many files to open at once"
    },
    "Probes" : {
      "type" : "array",
      "items" : {
        "$ref" : "Probe.json#"
      },
      "minItems" : 1
    },
    "Kernels" : {
      "description" : "Collection of kernel specifications",
      "type" : "object",
      "properties" : {},
      "additionalProperties" : {
        "oneOf" : [
          {
            "$ref" : "DeltaKernel.json#"
          },
          {
            "$ref" : "GaussianKernel.json#"
          },
          {
            "$ref" : "SidesetKernel.json#"
          },
          {
            "$ref" : "LineKernel.json#"
          },
          {
            "$ref" : "GaussianEllipseKernel.json#"
          },
          {
            "$ref" : "GaussianLineSegmentKernel.json#"
          }
        ]
      },
      "minProperties" : 1
    }
  },
  "additionalProperties" : false
}

=== sandialabs/dgm/schemas/testResponse.json
{
  "Name" : "Response",
  "Verbosity" : 3,
  "Probes" : [ 
    { "Name": "a", "Kernel": "g", "File": "2d.anl" },
    { "Name": "b", "Kernel": "d", "Xs": [0.5, 0.75], "Ys": [1.0, 0.75] },
    { "Name": "c", "Kernel": "e", "Xs": [0.5, 0.75], "Ys": [1.0, 0.75] }, 
    { "Name": "d", "Kernel": "s", "Xs":[0.0], "Ys": [ 1.0 ] }
  ],
  "Kernels" : {
    "g" : { "Type": "Gaussian", "Standard deviation" : 1.0,
            "Number of standard deviations": 5  },
    "d" : { "Type": "Delta", "Average" : false },
    "s" : { "Type": "Sideset" },
    "e" : { "Type": "GaussianEllipse", "Default sigma": [ 1, 1, 2],
            "Number of standard deviations": 3,
            "Default derivative": [0, 0],
            "Default direction": [[1,0],[0,1]] },
    "l" : { "Type": "GaussianLineSegment", "Standard deviation":0.2,
            "Number of standard deviations": 3 }
  }
}

=== sandialabs/dgm/runs/probes/linkedProbe/probes.json
{
  "Name" : "DomainResponse",
    "Verbosity": 1,
    "Kernels" : {
      "G0" : { "Type" : "Gaussian", "Standard deviation" : 0.2,
        "Number of standard deviations" : 3 },
      "D0" : { "Type" : "Delta", "Average" : true },
      "E0" : { "Type" : "GaussianEllipse",
        "Default sigma" : [ 0.2, 0.3 ],
        "Default derivative" : [ 0, 0 ],
        "Default direction" : [ [1.0, 0.0], [0.0, 1.0] ] },
      "L0" : { "Type" : "Line" },
      "GL" : { "Type" : "GaussianLineSegment", "Standard deviation" : 0.2,
        "Number of standard deviations" : 3 },
      "SS" : { "Type" : "Sideset" }
    },
    "Probes": [
    { "Name" : "d", "Kernel" : "D0", "File" : "2d.anl" },
    { "Name" : "g", "Kernel" : "D0",
      "Xs": [ 0.5, 0.75 ], "Ys": [ 1.0, 0.75 ] },
    { "Name" : "f", "Kernel" : "G0", "File" : "2d.f.anl" },
    { "Name" : "e", "Kernel" : "E0", "Xs": [ 0.5 ], "Ys": [ 1.0 ],
      "Direction" : [ [[1.0,0.0], [0.0,1.0]] ] },
    { "Name" : "j", "Kernel":"D0", "Format" : "Json", "File" : "2d.j.anl" },
    { "Name" : "s", "Kernel" : "GL",
      "Segments" : [ [[0.5, 1.0],[0.75,1.0]],
      [[1.0, 0.5],[1.0,0.75]] ] }
  ]
}
